apiVersion: v2
name: trustdidweb-server-py
icon: https://identity.foundation/trustdidweb/tdw.jpg
description: An api server to register and serve trusted web dids.
type: application
version: 0.0.10
appVersion: "0.0.6"

maintainers:
  - name: PatStLouis
    email: patrick.st-louis@opsecid.ca
    url: https://github.com/PatStLouis

dependencies:
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
  - name: common
    repository: https://charts.bitnami.com/bitnami/
    tags:
      - bitnami-common
    version: 2.x.x
