---
nameOverride: "didwebvh-server"
fullnameOverride: "didwebvh-server"

selectorLabels: {}

ingress:
  tls: []
  labels: []
  annotations: []

networkPolicy:
  ingress:
    namespaceSelector: []

server:
  image:
    repository: ghcr.io/decentralized-identity/didwebvh-server-py
    tag: 0.1.1
    pullPolicy: IfNotPresent
    pullSecrets: []
  # host is required when enabling TLS in the ingress
  # host: server.myapp.example

  environment:
    ENDORSER_MULTIKEY: ""

  replicaCount: 1

  podAnnotations: {}
  podSecurityContext: {}
  containerSecurityContext: {}

  service:
    type: ClusterIP
    apiPort: 8000
    servicePort: 8000

  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 128Mi

  networkPolicy:
    ingress:
      podSelector: {}

postgresql:
  enabled: true
  fullnameOverride: "didwebvh-server-postgresql"
  nameOverride: "didwebvh-server-postgresql"
  architecture: standalone
  auth:
    enablePostgresUser: true
    existingSecret: ""
    secretKeys:
      adminPasswordKey: admin-password
      userPasswordKey: database-password
    username: "didwebvh-server"

  ## PostgreSQL Primary parameters
  primary:
    persistence:
      enabled: true
      size: 1Gi
    containerSecurityContext:
      enabled: false
    podSecurityContext:
      enabled: false
    resources:
      limits:
        cpu: 800m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
    service:
      ports:
        postgresql: 5432
    extendedConfiguration: |
      max_connections = 500

  networkPolicy:
    ingress:
      podSelector: {}
