---
services:
  webvh-server:
    build:
      context: ../server
      dockerfile: Dockerfile
    environment:
      DOMAIN: ${WEBVH_DOMAIN}
      WEBVH_WITNESS: false
      WEBVH_PREROTATION: false
      WEBVH_PORTABILITY: false
      WEBVH_ENDORSEMENT: false
  
  demo_script:
    build:
      context: .
      dockerfile: Dockerfile.script
    environment:
      WATCHER_URL: ${WATCHER_URL}
      WATCHER_API_KEY: ${WATCHER_API_KEY}
      WEBVH_SERVER_URL: https://${WEBVH_DOMAIN}
      AGENT_ADMIN_API_URL: http://witness-agent:8020
    depends_on:
      witness-agent:
        condition: service_healthy

  ngrok:
    image: ngrok/ngrok:latest
    command: ["http", "webvh-server:8000", "--domain=${WEBVH_DOMAIN}"]
    environment:
      NGROK_AUTHTOKEN: ${NGROK_TOKEN}