---
admin: [0.0.0.0, 8020]
inbound-transport:
   - [ws, 0:0:0:0:0:0:0:0, 8021]
   - [http, 0:0:0:0:0:0:0:0, 8022]
outbound-transport: [ws, http]

no-ledger: true

auto-provision: true
recreate-wallet: false

wallet-type: askar-anoncreds
# wallet-storage-type: postgres_storage

multitenant: true
multitenant-admin: true

auto-ping-connection: true
auto-accept-invites: true
auto-accept-requests: true
auto-respond-messages: true

auto-store-credential: true

auto-respond-credential-offer: true
auto-respond-credential-request: true
auto-respond-credential-proposal: true

auto-verify-presentation: true
auto-respond-presentation-request: true

preserve-exchange-records: true

plugin:
  - webvh

# plugin-config-value:
#   - multitenant_provider.manager.always_check_provided_wallet_key=true
#   - multitenant_provider.manager.class_name="multitenant_provider.v1_0.manager.BasicMultitokenMultitenantManager"