name: Ruff Code Formatter and Linting Check

on:
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Ruff Format and Lint Check
        uses: astral-sh/ruff-action@v3
        with:
          src: "./server"
          version: "0.9.1"
          args: "format --check"